name: CI - SvelteKit Check and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: packages/pickr6-svelte

      - name: Run Check
        run: bun run check
        working-directory: packages/pickr6-svelte

      - name: Run Lint
        run: bun run lint
        working-directory: packages/pickr6-svelte

      - name: Build
        run: bun run build
        working-directory: packages/pickr6-svelte
